# Generated by Django 4.2.14 on 2024-08-22 15:48

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('stars', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_first_name', models.CharField(max_length=100)),
                ('applicant_last_name', models.CharField(max_length=100)),
                ('applicant_email', models.EmailField(default=0, max_length=254)),
                ('applicant_phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('cv', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='file')),
                ('status', models.IntegerField(choices=[(0, 'Applied'), (1, 'Sent to Employer'), (2, 'Accepted'), (3, 'Rejected')])),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Specialities',
            },
        ),
    ]
