# Generated by Django 4.2.14 on 2024-08-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applicant_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.IntegerField(choices=[(0, 'Applied'), (1, 'Sent to Employer'), (2, 'Accepted'), (3, 'Rejected')], default=0),
        ),
    ]
